name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MacTeX (no GUI) # Required for pdflatex
      run: brew install --cask mactex-no-gui

    - name: Install ImageMagick
      run: brew install imagemagick

    - name: Run all
      run: make all
