name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make texlive-full ghostscript

    - name: Build Resume
      run: make all
      
    - uses: actions/upload-artifact@v2
      with:
        name: resume-artifacts
        path: |
          *.pdf
          *.png